### ISSUE TITLE
Center command not working properly

### ISSUE THREAD

**Issue by indseta** [PotatoPresident/worldborderfixer#1]
On 1.16.5 the /worldborder center command doesn't work correctly in nether, it puts the center at the wrong location

**Comment by PotatoPresident** [comment]
Hmm.. After spending hours on this it seems to be a very complex issue. Might be a while while. Until then, if you need to set it in the nether, try multiplying the coordinates by 8 .

**Comment by indseta** [comment]
No problem, Ill wait, but the multiplying by 8 didnt work either btw
