### ISSUE TITLE
Possible issue with dimension mods (low priority)

### ISSUE THREAD

**Issue by EvieTheOwl** [PotatoPresident/worldborderfixer#2]
**Description:** Happens when the server shuts down, seems to be an issue with the Starry Skies fabric mod but i'm guessing could be a general issue or just an issue with fabric dimension mods in general
**Log:**https://gist.github.com/profjb58/d346c316aea7293cc1513f7ed01cdb23

**Comment by PotatoPresident** [comment]
Did some testing and was unable to reproduce this. Starry Skies world borders worked and saved without issue. Could you check the /world/dimensions/starry_sky/starry_sky_end/datafolder and see if worldBorder.dat exists? The error claims that it doesn't but that shouldn't be possible. If it does, maybe delete it?

**Comment by EvieTheOwl** [comment]
It does and the error doesn't exist now but this happened straight after we reset the world. Wondering if this could be an issue whereby the starry skies end dimension isn't loaded until the player enters it the first time and hence that's what produces the issue.
If it generates worldborder files regardless of the dimension is loaded by a player for the first time i'm not sure what's up tbh
