### ISSUE TITLE
World borders in the nether gets kinda funky

### ISSUE THREAD

**Issue by Laifsyn** [PotatoPresident/worldborderfixer#4]

**Comment by olliedavo** [comment]
yeah so i managed to figure out that if you devide the nether co-ordinates you want to set a world border for by 8 then you can get the physical wolrd border to show up there. however within the peramertars of the border you cant place or mine blocks and take damage. so even though it loks like your in the border your actually out of it.

**Comment by BorretSquared** [comment]
Same issue for me.

**Comment by PotatoPresident** [comment]
Fixed in 1.6.2

**Comment by Trixtail** [comment]
Still not fixed in version 1.6.2 on Fabric 1.20.1
