### ISSUE TITLE
Console Command

### ISSUE THREAD

**Issue by Jh16** [PotatoPresident/worldborderfixer#7]
Hello, can this mod specify different world borders through the console instead of through the player?

I'm wanting to automate the world borders through scheduling in my server panel. But the only command I can find with this mod is just `/worldborder`

**Comment by PotatoPresident** [comment]
Use /execute in

**Comment by Jh16** [comment]
Oh wow that was a fast reply!

So an example of this would look like?
`/execute in overworld worldborder`

**Comment by PotatoPresident** [comment]
Lol, was on GitHub

Yeah `/execute in minecraft:overworld run worldborder`
